name: Deploy to WordPress SVN

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Subversion
        run: sudo apt-get install -y subversion

      - name: Deploy to WordPress SVN
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          # Check out the WordPress SVN repo
          svn checkout https://plugins.svn.wordpress.org/qookieqloud wp-svn

          # Sync the plugin code to the trunk directory
          rsync -av --delete ./ wp-svn/trunk/ --exclude '.git*' --exclude '.github' --exclude 'svn-assets'

          # Sync the svn-assets directory to the assets directory in the SVN repo
          if [ -d "svn-assets" ]; then
            rsync -av --delete ./svn-assets/ wp-svn/assets/
          fi

          # Go into the SVN directory
          cd wp-svn

          # Add new files and mark deleted ones for SVN
          svn add --force * --auto-props --parents --depth infinity -q
          svn delete --force $(svn status | grep '^!' | awk '{print $2}') || true

          # Commit changes to the SVN repository
          svn commit -m "Deploying version ${GITHUB_REF_NAME}"
